import Head from 'next/head'
import { Page } from '@geist-ui/core'

type LayoutPropsType = {
  children: React.ReactNode,
}

function Layout({ children }: LayoutPropsType) {
  return (
    <>
      <Head>
        <title />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Page>
        <Page.Content>
          { children }
        </Page.Content>
      </Page>
    </>
  )
}

export default Layout
