import Head from 'next/head'
import { Page } from '@geist-ui/core'

function Layout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <Head>
        <title />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Page>
        { children }
      </Page>
    </>
  )
}

export default Layout
