import Head from 'next/head'
import { Page } from '@geist-ui/core'
import ThemeSelect from './ThemeSelect'

type LayoutPropsType = {
  children: React.ReactNode,
  currentTheme: string,
  onSwitchTheme: (theme: string) => void,
}

function Layout({ children, currentTheme, onSwitchTheme }: LayoutPropsType) {
  return (
    <>
      <Head>
        <title />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Page>
        <Page.Header center style={{ padding: '10px' }}>
          <ThemeSelect onSelect={onSwitchTheme} defaultValue={currentTheme} />
        </Page.Header>
        <Page.Content>
          { children }
        </Page.Content>
      </Page>
    </>
  )
}

export default Layout
